[package]
name = "ruva"
version = "0.1.52"
edition = "2021"
license = "MIT"
description = "Rust Library For Event Driven Message Handling"
repository = "https://github.com/BeringLab/ruva"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
ruva-core = { version = "0.1.52", path = "./ruva-core" }
ruva-macro = { version = "0.1.52", path = "./ruva-macro" }
static_assertions = "1.1.0"

[[example]]
name = "example1"
crate-type = ["bin"]
path = "example1/main.rs"
